# Generated by Django 4.1 on 2024-04-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_transaction_id_alter_order_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="transaction_id",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
